services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    volumes:
      - ${VOLUMES_PATH}/azurite/data:/data
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      - my_func_net
networks:
  my_func_net:
    driver: bridge
