services:
  aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:latest
    ports:
      - 18888:18888
      - 18889:18889
      - 18890:18890
    environment:
      - DASHBOARD__OTLP__AUTHMODE=ApiKey
      - DASHBOARD__OTLP__PRIMARYAPIKEY=${ASPIRE_DASHBOARD_OTLP_PRIMARYAPIKEY}
      - Dashboard:Frontend:AuthMode=Unsecured
      - DASHBOARD__TELEMETRYLIMITS__MAXLOGCOUNT=150000
      - DASHBOARD__TELEMETRYLIMITS__MAXTRACECOUNT=150000
      - DASHBOARD__TELEMETRYLIMITS__MAXMETRICSCOUNT=100000
      - DASHBOARD__OTLP__CORS__ALLOWEDORIGINS=*
    networks:
      - my_func_net
  