services:
  example-function-app1:
    image: ${EXAMPLE_FUNCION_APP1_IMAGE}
    platform: linux/amd64
    ports:
      - "${EXAMPLE_FUNCION_APP1_HTTP_PORT}:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=${DOTNET_ENVIRONMENT:-production}
      - OTEL_SERVICE_NAME=${EXAMPLE_FUNCION_APP1_OLTP_APP_NAME}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - AspiredDashboardOptions__PrimaryApiKey=${ASPIRE_DASHBOARD_OTLP_PRIMARYAPIKEY}
      - AzureWebJobsStorage=${AZURITE_CONNECTION_STRING}
    depends_on:
      - azurite
    networks:
      - my_func_net
